---
- name: Role Rehoming
  hosts: TEP1MU
  connection: network_cli
  gather_facts: false
  
  roles:
    - rehoming
  tags:
    - ssh
    
- name: Prueba telnet
  hosts: Telnet
  gather_facts: no

  roles:
    - rehoming
  tags:
    - telnet